Particular/NServiceBus.NHibernate

- packaging/nuget/nservicebus.nhibernate.nuspec
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/App_Packages/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/packages.config
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/BasicMessaging/When_using_a_message_with_TimeToBeReceived_has_expired.cs
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/Versioning/When_publishing_multiversioned_message.cs
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/packages.config
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.PerformanceTests/packages.config
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_fetching_timeouts_from_storage.cs
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_removing_timeouts_from_the_storage.cs
- src/NServiceBus.NHibernate.Tests/packages.config
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Persistence/ConfigureNHibernate.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutStorage.cs
- src/NServiceBus.NHibernate/packages.config
Implement the IPersistTimeoutsV2 interface in order to fix loosing timeout messages when not using dtc.
see issue https://github.com/Particular/NServiceBus/issues/2885
Connects to Particular/NServiceBus#2885
> implement IPersistTimeoutsV2 interface

- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1509/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_saga_contains_nested_collection_with_row_version.cs
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/InMemoryDBFixture.cs
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_removing_timeouts_from_the_storage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
Replacement for #154 
General idea: in V5 the methods on `TimeoutPersister`  had some fancy clever code that would hook up to an existing `SqlConnection` or `TransactionScope`. In V6 I dropped them in favor of just opening a new session each time within a suppressing scope. That change broke *exactly-once* configuration where the correctness depends on being able to have atomic receive and storage operation. This pull attempts to correct this mistake by re-using the synchronized storage adapter which already implements the mentioned "fancy clever code".
> Fixed handling of transactions in Add and TryRemove methods

- src/NServiceBus.NHibernate/Obsoletes/NHibernateStorageContext.cs
- src/NServiceBus.NHibernate/SharedConfig.cs
I've made two sessions that are no-op / not supported as obsolete.
> Marking custom session initialization and access obsolete.

- src/NServiceBus.NHibernate.Tests/SagaPersister/When_persisting_a_saga_with_a_unique_property.cs
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/SynchronizedStorage/TestingNHibernateSynchronizedStorageSession.cs
Connects to Particular/NServiceBus.Testing#29
This pull adds a storage session implementation that can be used only for testing handlers that uses NServiceBus-managed NHibernate session.
> Added a storage session class that enables testing of NH handlers

- src/NServiceBus.NHibernate/Deduplication/Installer/Installer.cs
- src/NServiceBus.NHibernate/Subscriptions/Installer/Installer.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/Installer/Installer.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/Installer/Installer.cs
@Particular/nservicebus-maintainers this fixes a bug introduced in #187
We no longer assume the defaults to be applied
cc @HEskandari
@Particular/nhibernate-persistence-maintainers please review
> SchemaUpdater can be not present in setting

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
https://github.com/Particular/NServiceBus/pull/3932
> TimeoutsChunk uses array for timeouts and timeouts is a struct to reduce garbage

- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/When_registering_managed_session_in_container.cs
- src/NServiceBus.NHibernate/SharedSession/NHibernateStorageSession.cs
Resolves https://github.com/Particular/NServiceBus.NHibernate/issues/209
:-1: to backporting. This is applicable to a very specific class of user, and there is a workaround available too (manually register the ISession in the container).
Ping @Particular/nhibernate-persistence-maintainers
> Change the ISession lifecycle to instance per UOW

- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/Subscriptions/SubscriptionPersister.cs
The subscription storage has an Init method which is never called. The core allows implementing `IInitializableSubscriptionStorage`. Then the core calls init on that type. I'm binding the class directly to the container. In theory with the interface scanning it should work. 
Happy to change it to the interface if you prefer.
@Particular/nhibernate-persistence-maintainers please review
> Initialize the subscription storage

- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateAmbientTransactionSynchronizedStorageSession.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateLazyNativeTransactionSynchronizedStorageSession.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateNativeTransactionSynchronizedStorageSession.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateSynchronizedStorage.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateSynchronizedStorageAdapter.cs
@ramonsmits @Particular/nhibernate-persistence-maintainers please review. This makes the synchronized storage session lazy (similar to V5 behavior).
> Made synchronized storage session lazy

- src/NServiceBus.NHibernate.Tests/SagaPersister/When_automapping_sagas.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
Hi Everyone,
We've just released `NServiceBus.NHibernate` `7.0.1`
As part of this release we had [7 commits](https://github.com/Particular/NServiceBus.NHibernate/compare/7.0.0...7.0.1) closing [1 issue](https://github.com/Particular/NServiceBus.NHibernate/issues?milestone=38&state=closed) closed.
__Fixed bugs__
- [__#239__](https://github.com/Particular/NServiceBus.NHibernate/issues/239) Saga mapping will auto map all types when the types to scan contains type System.Object
You are affected if
* You want to use auto mapped sagas but have a handler that processes messages of type System.Object (`IHandleMessages<object>`).
Some exceptions that can occur immediately at startup of the endpoint.
InvalidCastException:
>  System.InvalidCastException: Unable to cast object of type …
> Hotfix 7.0.1

- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
- src/NServiceBus.NHibernate/RepeatedFailuresOverTimeCircuitBreaker.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
Quick draft to resolve https://github.com/Particular/NServiceBus.NHibernate/issues/241
I have put the circuit breaker creation in the cleaner as that already contains configuration. In core circuitbreakers are created in the feature which seems to make more sense but that felt strange to do here unless that configuration value retrieval code is moved to the feature too.
> Outbox cleanup circuit breaker

- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
- src/NServiceBus.NHibernate/RepeatedFailuresOverTimeCircuitBreaker.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
* Imported RepeatedFailuresOverTimeCircuitBreaker, removed unneeded code and used it in OutboxCleaner as that also does other initialization.
* Simplify critical error message
* Format code
* Extract time parametes into constants
> Outbox cleanup circuit breaker (#242)

- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateAmbientTransactionSynchronizedStorageSession.cs
When [business data access with NHibernate persistence](https://docs.particular.net/nservicebus/nhibernate/accessing-data) fails, the database connection opened for the failed NHibernate session will not be closed.
Consistent rate of data access errors leads to ADO .NET connection pool exhaustion and endpoint shutdown.
Users of NHibernate persistence that use `SynchronizedStorageSession` are affected.
Related to #255
> Close connection even if session flush throws

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutEntityMap.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
NHibernate persistence uses `Guid.NewGuid()` method to generate identifiers when [storing timeout messages](https://docs.particular.net/nservicebus/messaging/timeout-manager#storing-timeout-messages). This results in index fragmentation and low performance of operations on the `TimeoutEntity` table.
Users of NHibernate persistence that use [delayed delivery](https://docs.particular.net/nservicebus/messaging/delayed-delivery), [delayed retries](https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries) or [saga timeouts](https://docs.particular.net/nservicebus/sagas/timeouts) are affected on all transports other than [Azure Service Bus](https://docs.particular.net/nservicebus/azure-service-bus/).
> Use CombGuid as timeout identifier

- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/When_using_outbox_and_wrapping_handlers_in_tx_scope.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_using_outbox_with_transport_in_transaction_scope_mode.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_using_transaction_scope_and_outbox.cs
- src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateSynchronizedStorageAdapter.cs
Originally reported in #269
Data changes done via synchronized storage session are lost and the incoming message is consumed. Resulting outgoing messages are dispatched normally resulting in ghost messages.
User's who use Outbox and (e.g. accidentally) enable `WrapHandlersInATransactionScope`.
> WrapHandlersInATransactionScope causes synchronized session transaction to lose data

- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.Tests/SagaPersister/InMemoryFixture.cs
- src/NServiceBus.NHibernate.Tests/SagaPersister/When_automapping_sagas_with_different_correlation_properties.cs
- src/NServiceBus.NHibernate.Tests/SagaPersister/When_persisting_a_saga_with_a_unique_property.cs
- src/NServiceBus.NHibernate.sln
- src/NServiceBus.NHibernate/Deduplication/NHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
Fixed appication of Unique constraing on saga correlation properties
Use optimized schema update to ensure correct indexes are created.
> Unique constraints are not generated for saga correlation properties

- src/NServiceBus.NHibernate.Tests/DDL.GatewayDeduplication.approved.txt
- src/NServiceBus.NHibernate.Tests/DDL.MySaga.approved.txt
- src/NServiceBus.NHibernate.Tests/DDL.Outbox.approved.txt
- src/NServiceBus.NHibernate.Tests/DDL.Subscriptions.approved.txt
- src/NServiceBus.NHibernate.Tests/DDL.Timeouts.approved.txt
- src/NServiceBus.NHibernate.Tests/GenerateSciptsTest.cs
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.Tests/app.config
- src/NServiceBus.NHibernate.Tests/packages.config
- src/NServiceBus.NHibernate.sln
- src/NServiceBus.NHibernate.sln.DotSettings
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/SagaPersisters/NHibernateSagaStorage.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
- src/NServiceBus.NHibernate/ScriptGenerator.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/OptimizedSchemaUpdate.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/SchemaFixUpHelper.cs
Adds `ScriptGenerator` class that can be used in tests to generate table creation scripts.
The `DDL.cs` test contains an example of how this would be used by users to generate their schemas as part of the build process.
> Script generator usable in a test

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
I've reviewed the changes in https://github.com/Particular/NServiceBus.NHibernate/pull/113 compared to the current code in the release branch. Result is this PR which adds one missing change: better use of the index in the query for next time to look for timeouts.
Replaces https://github.com/Particular/NServiceBus.NHibernate/pull/113
> Ramon's timeout improvements, re-applied

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/TestSuiteConstraints.cs
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/TestSuiteConstraints.cs
using the `AcceptanceTestingTransport` instead of the learning transport to disable native pubsub and native delayed delivery. This allows the acceptance tests to test the actual storage options.
> Use AcceptanceTestingTransport to test timeout and subscription storage

- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
The latest version of ApprovalTests has introduced a breaking change in a patch version, so we need to lock to the 3.0.13 release instead.
@ramonsmits This should be merged before #332 to fix the build error.
> Fix build error caused by ApprovalTests

- src/NServiceBus.NHibernate.AcceptanceTests/When_receiving_a_message_with_customized_outbox_table_name.cs
- src/NServiceBus.NHibernate.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.NHibernate/Outbox/OutboxConfig.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
I revived old PR by @ramonsmits . Added tests and merged the table and schema API calls into one method that overrides both (schema being optional).
> Override outbox table and schema names

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.PersistenceTests/NServiceBus.NHibernate.PersistenceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Outbox/ConcurrencyControlStrategy.cs
Implementation must use `.ToArray` that allocates a new array.
Unfortunately the DataContractJsonSerializer does not seem to support any of the low allocation memory types from System.Memory.
Strategies tried but non working
- ReadOnlyMemory<byte> property
- MemoryMarshal.TryGetArray, but destination is `byte[]` and gets the whole buffer. No way to get only the actual byte[] segment
- ReadOnlySpan<byte> property
- IEnumerable<byte>
> Support ReadOnlyMemory<byte> in transport operations

- src/NServiceBus.NHibernate.Tests/SynchronizedStorage/NHibernateSynchronizedStorageSessionTests.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateSynchronizedStorageSession.cs
If something during opening the session goes wrong, any `using` or `finally` block will still dispose the synchronized session, which then throws an NRE because the internal session might not have been set. This will hide the original exception that caused the open operation to fail in the first place.
> Fix synchronized session dispose

- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
Test projects should have an explicit reference to their upstream dependencies for dependabot to update them. This ensures that tests always run against the latest versions and verify compatibility.
> Add tx session reference back to test projects

- src/NServiceBus.NHibernate.Tests/Outbox/RepeatedFailuresOverTimeCircuitBreakerTests.cs
- src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
- src/NServiceBus.NHibernate/RepeatedFailuresOverTimeCircuitBreaker.cs
Backport of:
-  #1287
Which fixes for the `release-10.1` branch:
- #1291
> Send failures could lock transport into single concurrency mode

- src/NServiceBus.NHibernate.Tests/Outbox/RepeatedFailuresOverTimeCircuitBreakerTests.cs
- src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
- src/NServiceBus.NHibernate/RepeatedFailuresOverTimeCircuitBreaker.cs
A port of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1066
> Serializing the arm/disarm actions is not enough. The state transition preceding the arm/disarm action must be captured in the lock as well, otherwise the state transitions could happen properly but then the arm/disarm actions could be executed by the processor in the wrong order, leaving the logic of the circuit breaker itself intact but the consequences of the arm/disarm actions in an incorrect state.
> I also added xdoc as a way to document that the arm/disarm actions are called within a lock, and to maybe pave the way for this to be used as a shared component.
> Fix race condition in RepeatedFailuresOverTimeCircuitBreaker
