- src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs
@SzymonPobiega and @johnsimons I ran a few tests on my machine and there is no noticable difference in the performance. Also having a task started in the background which could fail and then lead to an unobserved task exception is not really a good design. Please review and merge if OK
> Removing Task.StartNew inside SetAsDispatched

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> Using Save instead of SaveOrUpdate when storing timeouts, fixes #99

- src/NServiceBus.NHibernate/Deduplication/Installer/Installer.cs
- src/NServiceBus.NHibernate/Deduplication/NHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/Outbox/EntityMappings.cs
- src/NServiceBus.NHibernate/SharedSession/Installer.cs
- src/NServiceBus.NHibernate/SharedSession/NHibernateStorageSession.cs
- src/NServiceBus.NHibernate/Subscriptions/Installer/Installer.cs
- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/Installer.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
Attempts to solve #96 by registering the installers in the container
> Multi host enabled installers

- src/NServiceBus.NHibernate/FodyWeavers.xml
- src/NServiceBus.NHibernate/Internal/NHibernateConfigurationBuilder.cs
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Obsoletes/ConfigureNHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/Obsoletes/ConfigureNHibernateSagaPersister.cs
- src/NServiceBus.NHibernate/Obsoletes/ConfigureNHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/Obsoletes/ConfigureNHibernateTimeoutPersister.cs
- src/NServiceBus.NHibernate/packages.config
- src/nuget.config
So that I can get #122 to even build on TeamCity and have a baseline for acceptance tests that I think were broken before I got started.
> Update Fody, weavers, NuGetPackager

- packaging/nuget/nservicebus.nhibernate.nuspec
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/App_Packages/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/packages.config
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/BasicMessaging/When_using_a_message_with_TimeToBeReceived_has_expired.cs
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NServiceBus.AcceptanceTests/Versioning/When_publishing_multiversioned_message.cs
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/packages.config
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.PerformanceTests/packages.config
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_fetching_timeouts_from_storage.cs
- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_removing_timeouts_from_the_storage.cs
- src/NServiceBus.NHibernate.Tests/packages.config
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Persistence/ConfigureNHibernate.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutStorage.cs
- src/NServiceBus.NHibernate/packages.config
Connects to Particular/NServiceBus#2885
> implement IPersistTimeoutsV2 interface

- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Subscriptions/CachedSubscriptionPersister.cs
- src/NServiceBus.NHibernate/packages.config
Part of https://github.com/Particular/PlatformDevelopment/issues/610
> Added coderules

- src/NServiceBus.NHibernate.Tests/SagaPersister/InMemoryFixture.cs
- src/NServiceBus.NHibernate/Deduplication/Installer/Installer.cs
- src/NServiceBus.NHibernate/Deduplication/NHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/Subscriptions/Installer/Installer.cs
- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/Installer/Installer.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/Installer/Installer.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
Paves the way for Particular/NServiceBus#3467
> No longer using property injection

- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/When_persister_commit_takes_longer_than_dispatch_of_another_later_timeout.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_user_supplies_NH_Configuration.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> Added periodic timeouts cleanup

- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/When_persister_commit_takes_longer_than_dispatch_of_another_later_timeout.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_user_supplies_NH_Configuration.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> Added periodic timeouts cleanup.

- src/NServiceBus.NHibernate/Deduplication/Installer/Installer.cs
- src/NServiceBus.NHibernate/Deduplication/NHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/Subscriptions/Installer/Installer.cs
- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/Installer/Installer.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/Installer/Installer.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
Fixes #187 
Tested with the nhibernate sample
> Pass the install action via settings to avoid issues with containers

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/App_Packages/NSB.AcceptanceTests.6.0.0-beta0004/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.NHibernate.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0004/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.NHibernate.Tests/SagaPersister/When_automapping_sagas_with_abstract_base_class.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
* Also fixed acceptance tests.
Fixes #114
> Fixed mapping when saga data inherits from more than one abstract class

- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateSynchronizedStorageAdapter.cs
Removed the core responsible for sharing an instance of `SqlConnection`. Based on the changes done in https://github.com/Particular/NServiceBus.SqlServer/pull/252 the same goal will be achieved by having separate instances of `SqlConnection` in transport and in persistence provided that both use the same connection string. 
The key feature is early closing of transport connection that prevents DTC escalation when persistence connection is created.
> Removed the code that was responsible for sharing the connection instance

- src/NServiceBus.NHibernate.Tests/SagaPersister/When_persisting_a_saga_with_a_unique_property.cs
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/SynchronizedStorage/TestingNHibernateSynchronizedStorageSession.cs
Same as https://github.com/Particular/NServiceBus.NHibernate/pull/180 but targets the release branch as we need that for the RC.
> Added a storage session class that enables testing of NH handlers.

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> Make timeout manager next chunk slice calculation consistent with other persisters

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutEntityMap.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> Use CombGuid as timeout identifier

- src/NServiceBus.NHibernate.Tests/DDL.MySaga.approved.txt
- src/NServiceBus.NHibernate.Tests/GenerateSciptsTest.cs
- src/NServiceBus.NHibernate.Tests/SagaPersister/InMemoryFixture.cs
- src/NServiceBus.NHibernate/SagaPersisters/NHibernateSagaStorage.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
- src/NServiceBus.NHibernate/ScriptGenerator.cs
> Adds scripts for creating index on FKs when saga data contains child elements

- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
Related to https://github.com/Particular/PlatformDevelopment/issues/852
As described in the issue, decided to release with the next patch.
> Hotfix 6.2.9

- src/NServiceBus.NHibernate/SagaPersisters/SagaPersister.cs
pending https://github.com/Particular/NServiceBus/pull/4923
> Sagas should only be classes

- src/NServiceBus.NHibernate.AcceptanceTests/ConfigureNHibernateGatewayPersistenceExecution.cs
- src/NServiceBus.NHibernate.AcceptanceTests/GatewayTestSuiteConstraints.cs
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
To make sure the gateway storage is tested
> Add gateway acceptance tests

- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
This PR fixes a broken build of `master`
> Fix for Fody breaking build

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/packages.config
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransport/NServiceBus.NHibernate.AcceptanceTests-SqlTransport.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransport/packages.config
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/packages.config
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.PerformanceTests/packages.config
- src/NServiceBus.NHibernate.Tests/App.config
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.Tests/packages.config
- src/NServiceBus.NHibernate.sln.DotSettings
This updates development tooling on the `support-7.2` branch.
Note: It is okay for this to be squashed.
> Update development tooling

- src/NServiceBus.NHibernate.Tests/TimeoutPersister/When_checking_db_indexes.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutsIndexValidator.cs
> Fixing TimeoutManager index validator for quoted schemas

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
> Update NServiceBus.Core packages

- GitVersion.yml
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
> Update Particular.Packaging in master

- GitVersion.yml
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
> Update Particular.Packaging in release-8.1

- GitVersion.yml
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
> Update Particular.Packaging in release-8.2

- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in master

- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in release-8.3

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/When_saga_contains_nested_collection.cs
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate/TimeoutPersisters/OptimizedSchemaUpdate.cs
For your review @mauroservienti
> Update test projects to netcoreapp3.1 in release-8.2

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate/TimeoutPersisters/OptimizedSchemaUpdate.cs
For your review @mauroservienti
> Update test projects to NServiceBus 7.2.3 in release-8.3

- src/NServiceBus.NHibernate.Tests/Persistence/NHibernateConfigurationBuilderTests.cs
- src/NServiceBus.NHibernate/Deduplication/NHibernateGatewayDeduplication.cs
- src/NServiceBus.NHibernate/Internal/NHibernateConfigurationBuilder.cs
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
- src/NServiceBus.NHibernate/Outbox/OutboxCleaner.cs
- src/NServiceBus.NHibernate/SagaPersisters/NHibernateSagaStorage.cs
- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
- src/NServiceBus.NHibernate/Subscriptions/NHibernateSubscriptionStorage.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
- src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs
Fixes https://github.com/Particular/NServiceBus.NHibernate/issues/311
> Add diagnostics

- src/NServiceBus.NHibernate.AcceptanceTests/When_using_outbox_with_transaction_scope.cs
- src/NServiceBus.NHibernate.AcceptanceTests/When_using_transaction_scope_outbox_and_wrapping_handlers.cs
- src/NServiceBus.NHibernate.Tests/Outbox/When_adding_outbox_messages.cs
- src/NServiceBus.NHibernate.Tests/Outbox/When_using_transaction_scope.cs
- src/NServiceBus.NHibernate/Outbox/INHibernateOutboxTransaction.cs
- src/NServiceBus.NHibernate/Outbox/NHibernateLocalOutboxTransaction.cs
- src/NServiceBus.NHibernate/Outbox/NHibernateTransactionScopeTransaction.cs
- src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs
Fixes: https://github.com/Particular/NServiceBus.NHibernate/issues/467
Raised because of https://github.com/Particular/NServiceBus.Persistence.Sql/issues/504
> Fix transaction scope outbox to allow floating the transaction scope to user code

- src/NServiceBus.NHibernate.Tests/Persistence/NHibernateConfigurationBuilderTests.cs
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482
> target framework update

- src/NServiceBus.NHibernate.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.NHibernate.Tests/Outbox/When_adding_outbox_messages.cs
- src/NServiceBus.NHibernate.Tests/Outbox/When_using_transaction_scope.cs
- src/NServiceBus.NHibernate.Tests/SynchronizedStorage/NHibernateOutboxTransactionSynchronizedStorageSessionTests.cs
- src/NServiceBus.NHibernate/Outbox/IOutboxPersisterFactory.cs
- src/NServiceBus.NHibernate/Outbox/NHibernateLocalOutboxTransaction.cs
- src/NServiceBus.NHibernate/Outbox/NHibernateTransactionScopeTransaction.cs
- src/NServiceBus.NHibernate/Outbox/OutboxSettingsExtensions.cs
- src/NServiceBus.NHibernate/SynchronizedStorage/NHibernateStorageSession.cs
> Allow customization of transaction isolation level

- src/NServiceBus.NHibernate.Tests/ApprovalFiles/APIApprovals.Approve.approved.txt
- src/NServiceBus.NHibernate/obsoletes-v9.cs
Restored obsolete APIs `GenerateGatewayDeduplicationStoreScript`  which are being removed
> Obsolete APIs for next major

- .github/workflows/ci.yml
> Bump oracle action

- .github/workflows/ci.yml
- .github/workflows/release.yml
Workflow updates based on https://github.com/Particular/KeepTheLightsOn/issues/1103
> Workflow updates - main

- .github/workflows/ci.yml
- .github/workflows/release.yml
Workflow updates based on https://github.com/Particular/KeepTheLightsOn/issues/1103
> Workflow updates - 8.5

- src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs
> Improve exception info when users share types between sagas (#703)

- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/When_using_transactional_session_with_transactionscope.cs
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
- src/NServiceBus.NHibernate.TransactionalSession/NServiceBus.NHibernate.TransactionalSession.csproj
Backporting #971 to `release-9.0`
> Transaction.Current may not be set after opening the session

- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/When_using_transactional_session_with_transactionscope.cs
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
- src/NServiceBus.NHibernate.TransactionalSession/NServiceBus.NHibernate.TransactionalSession.csproj
Backporting #971 to `release-8.6`
> Transaction.Current may not be set after opening the session 

- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
Updates the release branch to use the latest Core version containing transactional session related fixes.
> Verify Core 8.x changes

- .github/workflows/ci.yml
Adds the credentials to the setup Oracle action
> Update CI to add the Docker credentials

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
Backporting #1145 to release-8.6
Fixes https://github.com/Particular/PlatformBugs/issues/1344
https://osv.dev/vulnerability/GHSA-fg4q-ccq8-3r5q
> Upgrade NHibernate package version from 5.2.7 to 5.5.2 for OSV GHSA-fg4q-ccq8-3r5q

- src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.PersistenceTests/NServiceBus.NHibernate.PersistenceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
Backporting #1145 to release-9.0
Fixes https://github.com/Particular/PlatformBugs/issues/1344
https://osv.dev/vulnerability/GHSA-fg4q-ccq8-3r5q
> Upgrade NHibernate package version from 5.3.13 to 5.5.2 for OSV GHSA-fg4q-ccq8-3r5q

- src/NServiceBus.NHibernate.AcceptanceTests.Oracle/NServiceBus.NHibernate.AcceptanceTests.Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests.SqlTransport/NServiceBus.NHibernate.AcceptanceTests.SqlTransport.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.PersistenceTests/NServiceBus.NHibernate.PersistenceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests/NServiceBus.NHibernate.TransactionalSession.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
- src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
Backporting #1145 to release-10.0
Fixes https://github.com/Particular/PlatformBugs/issues/1344
https://osv.dev/vulnerability/GHSA-fg4q-ccq8-3r5q
> Upgrade NHibernate package version from 5.5.0 to 5.5.2 for OSV GHSA-fg4q-ccq8-3r5q

- src/NServiceBus.NHibernate.AcceptanceTests.Oracle/NServiceBus.NHibernate.AcceptanceTests.Oracle.csproj
- src/NServiceBus.NHibernate.AcceptanceTests.SqlTransport/NServiceBus.NHibernate.AcceptanceTests.SqlTransport.csproj
- src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
- src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
- src/NServiceBus.NHibernate.TransactionalSession.Tests/NServiceBus.NHibernate.TransactionalSession.Tests.csproj
This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.PersistenceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.
> Upgrading to NUnit4 including all required dependencies
